import 'package:blood_donation/Models/Offer.dart';
import 'package:blood_donation/Shared/shared_types.dart';

List<Offer> offers = [
  Offer(
    id: '1',
    name: 'John Doe',
    description: 'Needs blood donation for urgent surgery.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'A+',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '2',
    name: 'Jane Doe',
    description: 'Donating blood to help a friend in need.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'B+',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '3',
    name: 'John Smith',
    description: 'Regular blood donor, committed to saving lives.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'O+',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '4',
    name: 'Emily Johnson',
    description: 'Looking for a blood donor for a child in need.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'AB-',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '5',
    name: 'David Lee',
    description: 'Donating blood to support cancer patients.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'A-',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '6',
    name: 'Olivia Taylor',
    description: 'Needs blood donation for a heart surgery.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'B-',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '7',
    name: 'Noah Miller',
    description: 'Donating blood to help with a blood disorder.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'AB+',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '8',
    name: 'Emma Brown',
    description: 'Looking for a blood donor for a newborn baby.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'O-',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '9',
    name: 'Ava Jones',
    description: 'Donating blood to support victims of natural disasters.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'A+',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '10',
    name: 'Ethan Davis',
    description: 'Needs blood donation for a bone marrow transplant.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'B+',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '11',
    name: 'Sophia Wilson',
    description: 'Donating blood to help with emergency surgeries.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'O+',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '12',
    name: 'Benjamin Carter',
    description: 'Looking for a blood donor for a sickle cell patient.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'AB-',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '13',
    name: 'Mia Johnson',
    description: 'Donating blood to support victims of accidents.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'A-',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '14',
    name: 'Lucas Taylor',
    description: 'Needs blood donation for a chronic illness.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'B-',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '15',
    name: 'Lily Miller',
    description: 'Donating blood to help with research on blood diseases.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'AB+',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '16',
    name: 'Oliver Brown',
    description:
        'Looking for a blood donor for a patient in need of a transfusion.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'O-',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '17',
    name: 'Isabella Jones',
    description: 'Donating blood to support victims of violence.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'A+',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '18',
    name: 'Jacob Davis',
    description: 'Needs blood donation for a rare blood disorder.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'B+',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.accepted,
  ),
  Offer(
    id: '19',
    name: 'Ava Wilson',
    description: 'Donating blood to help with medical emergencies.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'O+',
    userType: UserTypes.donor,
    donationStatus: DonationStatus.pending,
  ),
  Offer(
    id: '20',
    name: 'Ethan Carter',
    description: 'Looking for a blood donor for a patient in need of surgery.',
    image: 'assets/images/blood_donation.jpeg',
    bloodType: 'AB-',
    userType: UserTypes.recipient,
    donationStatus: DonationStatus.accepted,
  ),
];
